export { checkUniversityEntrance } from './checkUniversityEntrance'
export type { UEDeps } from './checkUniversityEntrance'
export { calcNceaLevel } from './calcNceaLevel'
export type { NceaLevelDeps } from './calcNceaLevel'
export { resolveQualificationByYear } from './resolveQualificationByYear'
export type { ResolveDeps } from './resolveQualificationByYear'
export { describeNewQualification, hasPublishedAssessmentRules } from './describeNewQualification'
